name: Pages

on:
  push:
    branches:
      - source # source branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: install hexo-renderer-less
        run: npm install hexo-renderer-less --save
      -name: install hexo-generator-feed
        run: npm install hexo-generator-feed --save
      -name: install hexo-generator-json-content
        run: npm install hexo-generator-json-content --save
      -name: install hexo-helper-qrcode
        run: npm install hexo-helper-qrcode --save
      # - name: Build
        # run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
