name: Pages

on:
  push:
    branches:
      - source # source branch

jobs:
  pages:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.8.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.8.0"

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm -v
      - run: npx hexo -v
      - run: npm install
      - name: hexo clean
        run: |
            npm run clean
      - name: hexo generate
        run: |
            npm run generate
      - name: Deploy
        run: |
          npm run deploy
        # uses: peaceiris/actions-gh-pages@v3
        # with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # publish_dir: ./public
